name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código na branch main
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Renomeia homePage.html para index.html
      - name: Renomear homePage.html para index.html
        run: mv frontend/html/homePage.html frontend/html/index.html

      # Passo de Debug: listar arquivos para confirmar a renomeação
      - name: Listar arquivos para debug
        run: ls -al frontend/html

      # Publicação do conteúdo da pasta frontend/html na branch gh-pages
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/html
